services:
  - type: web
    name: worktrack-server
    env: docker
    dockerfilePath: server/Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
  - type: web
    name: worktrack-client
    env: static
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
