services:
  - type: web
    name: worktrack-server
    runtime: docker
    rootDir: server
    dockerfilePath: Dockerfile
    plan: free
    autoDeployTrigger: commit
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Masterprompt011%40admin:Masterprompt011@cluster0.mbmtfym.mongodb.net/worktrack?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: worktrack-dev-secret
      - key: CLIENT_URL
        value: https://worktrack-client.onrender.com
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  - type: web
    name: worktrack-client
    runtime: static
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    envVars:
      - key: VITE_API_URL
        value: https://worktrack-server.onrender.com/api