services:
  - type: web
    name: worktrack-server
    runtime: docker
    rootDir: server
    dockerfilePath: Dockerfile
    plan: free
    autoDeployTrigger: commit
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://worktrack-client.onrender.com
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  - type: web
    name: worktrack-client
    runtime: docker
    rootDir: client
    dockerfilePath: Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: VITE_API_URL
        value: https://worktrack-server.onrender.com/api